---
- name: create mariadb volume
  containers.podman.podman_volume:
    name: "{{ mariadb_volume }}"
    state: present
    label:
      image: mariadb
      purpose: db
  tags:
    - mariadb

- name: run a mariadb container
  containers.podman.podman_container:
    name: dev_mariadb
    image: mariadb
    state: started
    ports: "{{ mariadb_host_port }}:3306"
    volume: "{{ mariadb_volume }}:/var/lib/mysql"
    env:
      MYSQL_ROOT_PASSWORD: "{{ mariadb_password }}"
  tags:
    - mariadb
  register: mariadb
  notify:
    - Reflect changed mariadb from_port number
    - Reflect changed mariadb to_port number
    - Open mariadb ports

- name: create mysql volume
  containers.podman.podman_volume:
    name: "{{ mysql_volume }}"
    state: present
    label:
      image: mysql
      purpose: db
  tags:
    - mysql

- name: run a mysql container
  containers.podman.podman_container:
    name: dev_mysql
    image: mysql
    state: started
    ports: "{{ mysql_host_port }}:3306"
    volume: "{{ mysql_volume }}:/var/lib/mysql"
    env:
      MYSQL_ROOT_PASSWORD: "{{ mysql_password }}"
  tags:
    - mysql
  register: mysql
  notify:
    - Reflect changed mysql from_port number
    - Reflect changed mysql to_port number
    - Open mysql ports

- name: create postgresql volume
  containers.podman.podman_volume:
    name: "{{ postgresql_volume }}"
    state: present
    label:
      image: postgresql
      purpose: db
  tags:
    - postgresql

- name: run a postgresql container
  containers.podman.podman_container:
    name: dev_postgresql
    image: postgres
    state: started
    ports: "{{ postgresql_host_port }}:5432"
    volume: "{{ postgresql_volume }}:/var/lib/postgresql"
    env:
      POSTGRES_PASSWORD: "{{ postgresql_password }}"
  tags:
    - postgresql
  register: postgresql
  notify:
    - Reflect changed postgresql from_port number
    - Reflect changed postgresql to_port number
    - Open postgresql ports